### ISSUE TITLE
[FEAT] When opening SonetPCPFilterQt window, it would be nice if automatically a default trip is selected for the given spacecraft.

### ISSUE THREAD

**Issue by horiaghionoiu** [horiaghionoiu/sonet_tfm_horia#30]
![#30](https://user-images.githubusercontent.com/46227956/101542368-9277be80-399a-11eb-95e9-e468f8b06edf.gif)

**Comment by cesaaargm** [comment]
esta chido. Como lo instalo? ayuda pv

**Comment by cesaaargm** [comment]
dw Qt Creator

**Comment by horiaghionoiu** [comment]
Aquí está la doc de Qt for Python https://doc.qt.io/qtforpython/api.html#basic-modules

**Comment by horiaghionoiu** [comment]
- I propose to read the selected tab in the QMainWindow (Earth-Masrs or Mars-Earth) when opening the SonetPCPFilterQt window, and to select the current selected tab as the default S/C and Trip selection in the SonetPCPFilterQt __init__ constructor.
![image](https://user-images.githubusercontent.com/46227956/103149167-f520d680-475e-11eb-9c33-4f614d21a609.png)

![image](https://user-images.githubusercontent.com/46227956/103149187-29949280-475f-11eb-8a54-2b0992f7b590.png)

**Comment by horiaghionoiu** [comment]
GRACIAS!
